language: ruby
rvm: 2.2.4
env:
  RACK_ENV=test
before_script:
  psql -c 'create database hh_mobile_api_test' -U postgres
script:
  bundle exec rake db:migrate RACK_ENV=test
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: g6uYUylleN/rPFuQW48KU48AqfiFEpndAAslik4z8iZwi04Ev0nbfJE41+iNdB7fspL+S2mXZdwBcSqiCRJoxdhmTClPU2KFHGyHtRYQoa58mDhbR88g6LOmByaYmRmh5YWfCjH8TNd9EGBuRHql40hY2mtk1ONqK+d3u7q/GAAOUVq10M/eEljgzIE/x6mYFd7Pr8OVFfaMz/fsBZ6NsJ0VaOA47AV3RWmACqy5mv6LtpQ7gdQyQBLZqlf0Rdra+jJcMP70+E8jXY7ucbzWwLojniXEvt0LO6HrMAAyuimG7pkMOwz7JqqYl+ipPyGR7cJHASkyZxWY+wmFVHSNbXZeIBl846tgrwDYJsCPgfbMS8lOmpc1gXoxR46zmXHrIcHzDwBBX6Jaq0kTaRAKutXKvAQAY+KxNWzLJftAOmKcVHO5AkmQ7g3dZ+HNPwwpSeiqVm/AllWuY+iCqEuPh4K6XHDbl+qN9yOezZ3FPyTKO17k8DdnDTt+RU7qxe52ziqYbug9HKL7hWXraY1fOU/41iN/U0FsokP71I2dndIwWcZgq3rV3y9J61IogEQU1/lorT3uJwC9lh9hbEPUM6H9c1oH1K03Kr9VcE04rW2R0ofOvFZpRpOCCazwaMJxyoi+I3HsPe2icVI6IxvcRcyRok39ai2d8uRH9vvFQMU=
