localhost:
  adapter: postgresql
  host: localhost
  username: corbin 
  database: hh_mobile_api_dev

development:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"]
  username: zjzsgyyfddbboc
  password: k7C-56qPIdD7aS5f6BKY6LzW1I
  database: d6jpkv7c6f1jci
